artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  s3_bucket_name: my-textsummarizer
  input_key: samsum_dataset/train/data-00000-of-00001.arrow
  output_key: samsum_dataset/processed/summary.arrow
  local_data_file: artifacts/data_ingestion/text_data.arrow

data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  all_required_files: ["train", "test", "validation"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion
  tokenizer_name: google/pegasus-cnn_dailymail

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation
  model_checkpt: google/pegasus-cnn_dailymail


model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation
  model_path: artifacts/model_trainer/pegasus-samsum-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv

