artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  s3_bucket_name: my-textsummarizer
  input_key: samsum_dataset/train/data-00000-of-00001.arrow
  output_key: samsum_dataset/processed/summary.arrow
  local_data_file: artifacts/data_ingestion/text_data.arrow

data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  all_required_files: ["train", "test", "validation"]

